from api.views.action import ActionViewSet
from api.views.product import ProductViewSet
from api.views.type import TypeViewSet
from api.views.user import UserViewSet
from api.views.cart import CartViewSet
from api.views.history import HistoryViewSet
from api.views.order import OrderViewSet
from api.views.comment import CommentViewSet
from api.views.reply import ReplyViewSet
