# Generated by Django 2.2.3 on 2019-10-10 13:09

from django.db import migrations, models
import rest_framework.compat


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, validators=[rest_framework.compat.MinValueValidator(1), rest_framework.compat.MaxValueValidator(10)]),
        ),
    ]
