# Generated by Django 2.2.3 on 2019-10-10 13:13

import django.core.validators
from django.db import migrations, models
import rest_framework.compat


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191010_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[rest_framework.compat.MinLengthValidator(9), django.core.validators.RegexValidator(message='A valid integer is required.', regex='^\\d+$')]),
        ),
    ]
