# Generated by Django 2.2.3 on 2019-10-12 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191010_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('products', models.CharField(blank=True, max_length=255, null=True)),
                ('totals', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='Đang chờ', max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_per_unit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
