# Generated by Django 2.2.3 on 2019-10-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191012_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='username',
            new_name='name',
        ),
        migrations.AddField(
            model_name='history',
            name='user_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
