# Generated by Django 2.2.3 on 2019-10-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20191014_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, default='Đang chờ', max_length=255, null=True),
        ),
    ]
