# Generated by Django 2.2.3 on 2019-10-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
