# Generated by Django 2.2.3 on 2019-11-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=255, null=True),
        ),
    ]
