# Generated by Django 2.2.3 on 2019-11-22 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='telephone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.RegexValidator(message='A valid integer is required.', regex='^\\d+$')]),
        ),
    ]
