# Generated by Django 2.2.3 on 2019-11-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20191123_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='type',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
