# Generated by Django 2.2.3 on 2019-11-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20191130_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='active',
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
