# Generated by Django 2.2.3 on 2019-11-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20191130_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
